stages:
  - iosbuild
  - mavenbuild
  - maventest
  - autodeploy

iosbuild_project:
  stage: iosbuild
  script:
    - xcodebuild test -project Frontend/iOSApp/CyTalk/CyTalk.xcodeproj -scheme CyTalk -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'
  tags:
    - ios_tag

maven-build:
  stage: mavenbuild
  tags:
    - back_tag
  script:
    - cd Backend/Springboot
    - mvn package -B
  only:
    changes:
    - Backend/**/*
  
maven-test:
  stage: maventest
  tags:
    - back_tag
  script:
    - cd Backend/Springboot
    - mvn test
  artifacts:
    paths:
      - Backend/Springboot/target/*.jar
  only:
    changes:
    - Backend/**/*
      
autoDeploy:
  stage: autodeploy
  tags:
   - back_tag
  script:
    - cd Backend/Springboot
    - mvn package
    - sudo mv target/*.jar /srv/springboot.jar 
    - sudo systemctl stop springboot
    - sudo systemctl start springboot
  only:
    refs:
    - master
    changes:
    - Backend/**/*