stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project CyTalk.xcodeproj -scheme SchemeName | xcpretty
    - xcodebuild test -project CyTalk.xcodeproj -scheme SchemeName -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0' | xcpretty -s
  tags:
    - ios_tag